apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secrets
type: Opaque
data:
  # user = superman@gmail.com 
  PG_USER_EMAIL: c3VwZXJtYW5AZ21haWwuY29t
  # password = estaEsMiClave
  PG_PASSWORD: ZXN0YUVzTWlDbGF2ZQ==
