version: '3'

services:

  # Nombre del servicio
  db:
    container_name: postgres_database   # Este tambien sería el hostname
    image: postgres:15.1
    volumes:
      # - postgres-db:/var/lib/postgresql/data  # Ejemplo
      - ./postgres/data:/var/lib/postgresql/data   # Bind Volume, se crea un directorio en el host
    environment:
      - POSTGRES_PASSWORD=123456

  pgAdmin:
    depends_on:
      - db
    image: dpage/pgadmin4:6:17
    ports:
      - "8080:80"
    volumen:
    - ./pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL: "juan@gmail.com"
      - PGADMIN_DEFAULT_PASSWORD: "123456"


volumes:
  postgres-db:   # Si no se define nada más, se creará un volumen nuevo
    # Para usar un volumen existente, se puede hacer:
    # external: true

